Fix install_requires by adding requests
astraw/stdeb pull request #126
Opened 2016-10-12 07:51 UTC by sebix

fixes astraw/stdeb#78

2019-04-17 07:40 UTC, jayvdb requested changes
This produces `/usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'`

2019-05-11 09:34 UTC, sebix commented
That only works with setuptools, not with distutils :/

Is there a specific reason why distutils is used and not the more widespread setuptools?

2025-08-28 21:19 UTC, nuclearsandwich commented
> Is there a specific reason why distutils is used and not the more widespread setuptools?

In the past, distutils was in the standard library whereas setuptools is not. However setuptools now vendors a distutils compatibility library and distutils itself is no longer part of the Python standard library so the reason not to use setuptools has diminished.

2025-08-28 21:23 UTC, nuclearsandwich commented
Closing this in favor of #207 which incorporates it into a switch to setuptools.

2025-08-28 21:23 UTC, closed without merging